import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronLeft, ChevronRight, ArrowRight, Plus, Minus, Search, Globe, ShieldCheck, Thermometer, CheckCircle2, Info } from "lucide-react";

// Icons for Topics
const CoralIcon = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="text-cyan-400">
    <path d="M12 22V11" />
    <path d="M12 16C9 14 7 11 7 8" />
    <path d="M12 14C15 13 17 10 17 7" />
    <circle cx="7" cy="8" r="1" fill="currentColor" />
    <circle cx="17" cy="7" r="1" fill="currentColor" />
    <circle cx="12" cy="5" r="1" fill="currentColor" />
  </svg>
);

const PlasticBottleIcon = () => (
  <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="text-cyan-400">
    <rect x="9" y="2" width="6" height="3" rx="1" />
    <path d="M10 5v2L7 9v11a2 2 0 002 2h6a2 2 0 002-2V9l-3-2V5" />
    <path d="M7 14h10" />
  </svg>
);

const FishIcon = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="text-cyan-400">
    <path d="M2 12c4-5 11-5 15 0l4-3v6l-4-3c-4 5-11 5-15 0z" />
    <circle cx="15" cy="10" r="1" fill="currentColor" />
  </svg>
);

const ClimateIcon = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="text-cyan-400">
    <path d="M14 4v10.5a3.5 3.5 0 1 1-4 0V4a2 2 0 1 1 4 0z" />
    <circle cx="18" cy="8" r="3" />
    <path d="M18 5v6" />
    <path d="M15 8h6" />
  </svg>
);

const ConservationIcon = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="text-cyan-400">
    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
    <path d="M8 12h8" />
    <path d="M8 12h8" />
  </svg>
);

const topics = [
  { id: "coral", label: "Coral Reefs", icon: CoralIcon },
  { id: "pollution", label: "Pollution", icon: PlasticBottleIcon },
  { id: "marine", label: "Marine Life", icon: FishIcon },
  { id: "climate", label: "Climate Change", icon: ClimateIcon },
  { id: "conservation", label: "Conservation", icon: ConservationIcon },
];

const topicDetails = {
  coral: {
    title: "Coral Reef Ecosystems",
    tagline: "The Rainforests of the Sea",
    description: "Coral reefs support over 25% of all marine life despite covering less than 1% of the ocean floor. They act as essential nursery grounds, coastal surge buffers, and ocean carbon sinks.",
    image: "/images/corals.webp",
    stats: [
      { label: "Marine Life Supported", value: "25%+" },
      { label: "Coastlines Protected", value: "71,000+ km" },
      { label: "Restoration Nurseries", value: "150+ Active" }
    ],
    bulletPoints: [
      "Symbiotic microalgae (Zooxanthellae) supply corals with 90% of their metabolic energy.",
      "Coral fragment nurseries accelerate coral growth up to 40x faster than natural wild reef speeds.",
      "Healthy reefs absorb up to 97% of incoming wave energy, shielding coastal communities from storms."
    ]
  },
  pollution: {
    title: "Marine Plastic & Waste Crisis",
    tagline: "Un-Plasticking Our Oceans",
    description: "Over 11 million metric tons of plastic waste enter global ocean waters annually. Ghost nets and microplastics degrade marine habitats and harm sea life across all abyssal depths.",
    image: "/images/Plastic bottle.webp",
    stats: [
      { label: "Annual Plastic Inflow", value: "11M Tons" },
      { label: "Microplastic Particles", value: "50 Trillion+" },
      { label: "Ghost Net Removal", value: "850+ Tons" }
    ],
    bulletPoints: [
      "Plastics break down into microscopic particles ingested by plankton, bioaccumulating up the food chain.",
      "Abandoned ghost nets continue trapping sea turtles and marine life for decades if left unextracted.",
      "Land-based river interception prevents up to 80% of plastic waste from reaching open ocean waters."
    ]
  },
  marine: {
    title: "Marine Biodiversity & Habitats",
    tagline: "Protecting Underwater Creatures",
    description: "From sea turtles and clownfish to sea otters and coral species, rich marine biodiversity is essential for stabilizing global ocean food webs and oxygen production.",
    image: "/images/clownfish.webp",
    stats: [
      { label: "Cataloged Species", value: "240,000+" },
      { label: "Endangered Marine Life", value: "2,200+ Species" },
      { label: "Oxygen Generated by Seas", value: "50% - 80%" }
    ],
    bulletPoints: [
      "Ocean phytoplankton produce over half of Earth's breathable oxygen through photosynthesis.",
      "Sea turtles maintain healthy seagrass beds and coral reef balances by grazing on sponges and jellyfish.",
      "Keystone species like sea otters protect underwater kelp forests that capture massive amounts of carbon."
    ]
  },
  climate: {
    title: "Ocean Climate Regulation",
    tagline: "Thermal Buffers & Acidification",
    description: "Oceans absorb 90% of excess global atmospheric heat. Rising water temperatures cause widespread coral bleaching, while excess CO2 increases seawater acidity.",
    image: "/images/coral_bleaching.webp",
    stats: [
      { label: "Excess Heat Absorbed", value: "90%" },
      { label: "CO2 Absorption Rate", value: "30% Global" },
      { label: "Ocean Acidity Rise", value: "+30% Since 1800s" }
    ],
    bulletPoints: [
      "Thermal stress causes corals to expel their algae partners, leading to bleaching and mass mortality.",
      "Ocean acidification weakens calcium carbonate shell formation for shellfish and reef structures.",
      "Deploying heat-tolerant coral strains creates climate-resilient sanctuaries capable of surviving warm swells."
    ]
  },
  conservation: {
    title: "Marine Conservation & Action",
    tagline: "Science-Driven Action",
    description: "Combining community mobilization, marine protected areas (MPAs), and robotic sea restoration to safeguard marine ecosystems for future generations.",
    image: "/images/action_ocean_bg.webp",
    stats: [
      { label: "Marine Protected Areas", value: "8.2% Globally" },
      { label: "2030 Global Target", value: "30% Ocean Protected" },
      { label: "Volunteers Deployed", value: "12,500+" }
    ],
    bulletPoints: [
      "Protected marine corridors allow wild fish stocks to replenish naturally and migrate safely.",
      "Community stewardship programs empower coastal villages with sustainable eco-tourism income.",
      "High-tech sonar mapping pinpoints optimal reef fragmentation sites."
    ]
  }
};

const explorerSlides = [
  {
    id: 1,
    title: "Great Barrier Reef",
    location: "Australia",
    image: "/images/corals.webp",
  },
  {
    id: 2,
    title: "Raja Ampat Coral Sanctuary",
    location: "Indonesia",
    image: "/images/raja_ampat.webp",
  },
  {
    id: 3,
    title: "Deep Abyssal Trench",
    location: "Pacific Ocean",
    image: "/images/deep ocean.webp",
  },
  {
    id: 4,
    title: "Galapagos Marine Reserve",
    location: "Ecuador",
    image: "/images/turtle.webp",
  },
];

const researchReports = [
  {
    id: 1,
    title: "Global Coral Reef Status Report 2024",
    image: "/images/staghorn_coral.webp",
  },
  {
    id: 2,
    title: "Microplastics in Our Oceans",
    image: "/images/Plastic bottle.webp",
  },
  {
    id: 3,
    title: "Rising Ocean Temperatures",
    image: "/images/coral_bleaching.webp",
  },
  {
    id: 4,
    title: "Sustainable Fisheries Report",
    image: "/images/clownfish.webp",
  },
];

const faqData = [
  {
    question: "Why are coral reefs important?",
    answer:
      "Coral reefs support over 25% of all marine species despite occupying less than 1% of the ocean floor. They shield coastal communities from storm surges, prevent erosion, and sustain global fishing economies.",
  },
  {
    question: "How does plastic harm marine life?",
    answer:
      "Plastic debris breaks down into microplastics that marine animals ingest, causing toxic bioaccumulation, entanglement, habitat degradation, and severe disruption of ocean ecosystems.",
  },
  {
    question: "What can I do to help?",
    answer:
      "You can reduce single-use plastic usage, support marine conservation initiatives, participate in beach cleanups, and advocate for sustainable seafood policies.",
  },
  {
    question: "How is REEF making a difference?",
    answer:
      "REEF actively restores damaged coral structures, removes marine debris, conducts scientific research, and empowers coastal communities through education and direct conservation programs.",
  },
];

const Learn = () => {
  const [selectedTopic, setSelectedTopic] = useState("coral");
  const [currentSlide, setCurrentSlide] = useState(0);
  const [openFaq, setOpenFaq] = useState(null);

  const activeTopicInfo = topicDetails[selectedTopic] || topicDetails.coral;

  const toggleFaq = (index) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % explorerSlides.length);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + explorerSlides.length) % explorerSlides.length);
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { 
      opacity: 1,
      transition: { staggerChildren: 0.1, delayChildren: 0.2 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } }
  };

  return (
    <div className="min-h-screen bg-[#040810] text-white pt-28 pb-16 px-6 md:px-12 lg:px-24 font-serif selection:bg-cyan-500 selection:text-slate-950 relative overflow-hidden select-none">
      
      {/* VIVID HEADER BACKGROUND IMAGE (Extends to 20px below subheading) */}
      <div className="absolute top-0 inset-x-0 h-[440px] sm:h-[480px] lg:h-[500px] z-0 overflow-hidden pointer-events-none">
        <img loading="lazy"
          src="/images/image.webp"
          alt="Ocean Environment"
          className="w-full h-full object-cover object-bottom opacity-85 brightness-105"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-[#040810]/50 via-black/20 to-[#040810]" />
        <div className="absolute bottom-0 inset-x-0 h-24 bg-gradient-to-t from-[#040810] to-transparent" />
      </div>

      {/* Subtle Ambient Background Elements */}
      <div className="absolute top-0 left-0 w-full h-full pointer-events-none z-0 fixed">
        <div className="absolute top-1/4 right-1/4 w-[400px] h-[400px] bg-cyan-950/30 rounded-full mix-blend-screen filter blur-[140px] opacity-20"></div>
        <div className="absolute bottom-1/3 left-1/3 w-[600px] h-[600px] bg-[#050c18] rounded-full mix-blend-screen filter blur-[160px] opacity-40"></div>
      </div>

      <motion.div 
        className="max-w-7xl mx-auto relative z-10"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {/* Header Section */}
        <motion.div 
          variants={itemVariants}
          className="text-center mb-16 max-w-4xl mx-auto"
        >
          <h3 className="text-cyan-300 uppercase tracking-[0.3em] text-xs sm:text-sm font-bold mb-6 drop-shadow-[0_2px_8px_rgba(0,0,0,0.9)]">
            Learn & Discover
          </h3>
          <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold leading-tight text-white mb-6 tracking-tight drop-shadow-[0_4px_16px_rgba(0,0,0,0.9)]">
            Learn. Explore. <br />
            <span className="font-light text-slate-200">Understand.</span>
          </h1>
          <p className="text-slate-100 text-base sm:text-lg max-w-2xl mx-auto leading-relaxed font-normal drop-shadow-[0_2px_10px_rgba(0,0,0,0.95)]">
            The more we know, the better we protect. Explore ocean guides, marine biology research, and ecosystem insights.
          </p>
        </motion.div>

        {/* Main Content Sections Space Out Cohesively */}
        <div className="space-y-12 sm:space-y-16">
          
          {/* 1. TOPICS SECTION (Fully Interactive) */}
          <motion.div variants={itemVariants} className="bg-[#050c18] border border-slate-800/80 rounded-3xl p-6 sm:p-10 shadow-2xl">
            <h2 className="text-xl sm:text-2xl font-bold text-white mb-6">Explore Topics</h2>
            
            {/* Topic Selection Buttons Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3 sm:gap-4 mb-8">
              {topics.map((topic) => {
                const IconComp = topic.icon;
                const isSelected = selectedTopic === topic.id;
                return (
                  <button
                    key={topic.id}
                    onClick={() => setSelectedTopic(topic.id)}
                    className={`flex flex-col items-center justify-center p-4 rounded-2xl border text-center transition-all duration-300 cursor-pointer ${
                      isSelected
                        ? "bg-[#08182c] border-cyan-400 text-cyan-200 shadow-[0_0_20px_rgba(34,211,238,0.35)] scale-[1.03]"
                        : "bg-[#060e1b]/80 border-slate-800/80 text-slate-400 hover:border-slate-700 hover:text-slate-200 hover:bg-[#071426]"
                    }`}
                  >
                    <div className={`w-12 h-12 rounded-full border flex items-center justify-center mb-2.5 transition-colors ${
                      isSelected ? "bg-cyan-950 border-cyan-400 text-cyan-300" : "bg-cyan-950/30 border-slate-800 text-slate-400"
                    }`}>
                      <IconComp />
                    </div>
                    <span className="text-xs sm:text-sm font-semibold leading-tight">
                      {topic.label}
                    </span>
                  </button>
                );
              })}
            </div>

            {/* Interactive Topic Content Card */}
            <AnimatePresence mode="wait">
              <motion.div
                key={selectedTopic}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.4 }}
                className="bg-[#060e1b]/90 border border-slate-800/80 rounded-2xl p-6 sm:p-8 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center"
              >
                {/* Left Info Column */}
                <div className="lg:col-span-7 flex flex-col justify-between h-full">
                  <div>
                    <span className="text-cyan-400 text-xs font-semibold uppercase tracking-widest block mb-2">
                      {activeTopicInfo.tagline}
                    </span>
                    <h3 className="text-2xl sm:text-3xl font-bold text-white mb-3">
                      {activeTopicInfo.title}
                    </h3>
                    <p className="text-slate-300 text-sm sm:text-base leading-relaxed mb-6 font-normal">
                      {activeTopicInfo.description}
                    </p>

                    {/* Stats Highlights */}
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-6 border-y border-slate-800/80 py-4">
                      {activeTopicInfo.stats.map((stat, idx) => (
                        <div key={idx} className="text-left">
                          <div className="text-cyan-300 font-bold text-base sm:text-xl">{stat.value}</div>
                          <div className="text-slate-400 text-[11px] sm:text-xs leading-tight mt-0.5">{stat.label}</div>
                        </div>
                      ))}
                    </div>

                    {/* Key Conservation Insights */}
                    <div className="space-y-2.5">
                      {activeTopicInfo.bulletPoints.map((point, idx) => (
                        <div key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-300">
                          <CheckCircle2 size={16} className="text-cyan-400 shrink-0 mt-0.5" />
                          <span>{point}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Right Image Feature Column */}
                <div className="lg:col-span-5 relative h-64 sm:h-80 rounded-2xl overflow-hidden border border-slate-800/80 shadow-lg group">
                  <img loading="lazy"
                    src={activeTopicInfo.image}
                    alt={activeTopicInfo.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-[#050c18] via-transparent to-transparent opacity-70" />
                  <div className="absolute bottom-4 left-4 right-4 bg-[#040810]/85 backdrop-blur-md border border-cyan-500/30 p-3 rounded-xl flex items-center justify-between text-xs text-slate-200">
                    <span className="font-semibold text-cyan-300">Active Conservation Topic</span>
                    <Info size={14} className="text-cyan-400" />
                  </div>
                </div>
              </motion.div>
            </AnimatePresence>

          </motion.div>

          {/* 2. OCEAN EXPLORER CAROUSEL */}
          <motion.div variants={itemVariants} className="bg-[#050c18] border border-slate-800/80 rounded-3xl p-6 sm:p-10 shadow-2xl text-center">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              Ocean Explorer
            </h2>
            <p className="text-slate-400 text-sm mt-1 mb-8">
              Dive into interactive ocean sanctuaries worldwide.
            </p>

            <div className="relative max-w-4xl mx-auto flex items-center justify-between gap-4">
              {/* Prev Arrow */}
              <button
                onClick={prevSlide}
                className="p-3 rounded-full bg-[#071324]/80 border border-slate-700 text-slate-300 hover:text-white hover:border-cyan-400 transition cursor-pointer shrink-0 z-10"
                aria-label="Previous Slide"
              >
                <ChevronLeft size={22} />
              </button>

              {/* Slide Card Display */}
              <div className="relative w-full h-[280px] sm:h-[340px] rounded-2xl overflow-hidden border border-slate-800/80 group">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={explorerSlides[currentSlide].id}
                    initial={{ opacity: 0, scale: 1.05 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    transition={{ duration: 0.5 }}
                    className="absolute inset-0"
                  >
                    <img
                      src={explorerSlides[currentSlide].image}
                      alt={explorerSlides[currentSlide].title}
                      loading="lazy"
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-[#050c18] via-[#050c18]/40 to-transparent" />

                    {/* Slide Content Overlay */}
                    <div className="absolute bottom-6 left-6 sm:bottom-10 sm:left-10 text-left">
                      <h3 className="text-xl sm:text-3xl font-bold text-white tracking-tight drop-shadow-md">
                        {explorerSlides[currentSlide].title}
                      </h3>
                      <p className="text-xs sm:text-sm text-slate-300 mt-1">
                        {explorerSlides[currentSlide].location}
                      </p>
                    </div>
                  </motion.div>
                </AnimatePresence>
              </div>

              {/* Next Arrow */}
              <button
                onClick={nextSlide}
                className="p-3 rounded-full bg-[#071324]/80 border border-slate-700 text-slate-300 hover:text-white hover:border-cyan-400 transition cursor-pointer shrink-0 z-10"
                aria-label="Next Slide"
              >
                <ChevronRight size={22} />
              </button>
            </div>

            {/* Dots Indicator */}
            <div className="flex justify-center items-center gap-2 mt-6">
              {explorerSlides.map((_, idx) => (
                <button
                  key={idx}
                  onClick={() => setCurrentSlide(idx)}
                  aria-label={`Go to slide ${idx + 1}`}
                  className={`transition-all duration-300 cursor-pointer ${
                    currentSlide === idx
                      ? "w-3 h-3 bg-cyan-400 rounded-full shadow-[0_0_8px_#22d3ee]"
                      : "w-2 h-2 bg-slate-600 rounded-full hover:bg-slate-400"
                  }`}
                />
              ))}
            </div>
          </motion.div>

          {/* 3. RESEARCH & REPORTS */}
          <motion.div variants={itemVariants} className="bg-[#050c18] border border-slate-800/80 rounded-3xl p-6 sm:p-10 shadow-2xl">
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight mb-1 text-center">
              Research & Reports
            </h2>
            <p className="text-slate-400 text-sm text-center mb-8">
              Latest marine studies and conservation findings.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {researchReports.map((report) => (
                <div
                  key={report.id}
                  className="bg-[#060e1b]/80 border border-slate-800/80 hover:border-cyan-500/50 rounded-2xl overflow-hidden flex flex-col justify-between transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_10px_30px_rgba(0,0,0,0.5)] group text-left"
                >
                  <div className="h-44 overflow-hidden relative">
                    <img
                      src={report.image}
                      alt={report.title}
                      loading="lazy"
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-[#060e1b] via-transparent to-transparent opacity-80" />
                  </div>

                  <div className="p-5 flex flex-col justify-between flex-1">
                    <h4 className="text-sm sm:text-base font-bold text-[#ffffff] leading-snug group-hover:text-cyan-300 transition">
                      {report.title}
                    </h4>

                    <div className="mt-6 pt-3 border-t border-slate-800/60">
                      <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-cyan-400 group-hover:text-cyan-200 transition">
                        Read Report <ArrowRight size={14} />
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>

          {/* 4. FREQUENTLY ASKED QUESTIONS */}
          <motion.div variants={itemVariants} className="bg-[#050c18] border border-slate-800/80 rounded-3xl p-6 sm:p-10 shadow-2xl">
            <h2 className="text-2xl sm:text-3xl font-bold text-white text-center tracking-tight mb-8">
              Frequently Asked Questions
            </h2>

            <div className="flex flex-col gap-3 max-w-3xl mx-auto">
              {faqData.map((faq, index) => {
                const isOpen = openFaq === index;
                return (
                  <div
                    key={index}
                    className="rounded-2xl bg-[#060e1b]/80 border border-slate-800/80 overflow-hidden transition duration-200"
                  >
                    <button
                      onClick={() => toggleFaq(index)}
                      className="w-full flex items-center justify-between p-5 text-left text-sm sm:text-base font-bold text-white hover:text-cyan-300 transition cursor-pointer"
                    >
                      <span>{faq.question}</span>
                      <div className="p-1 rounded-lg bg-slate-800/80 text-cyan-400 shrink-0 ml-4">
                        {isOpen ? <Minus size={18} /> : <Plus size={18} />}
                      </div>
                    </button>

                    <AnimatePresence>
                      {isOpen && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: "auto" }}
                          exit={{ opacity: 0, height: 0 }}
                          transition={{ duration: 0.3 }}
                          className="px-5 pb-5 text-xs sm:text-sm text-slate-300 leading-relaxed border-t border-slate-800/60 pt-3"
                        >
                          {faq.answer}
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                );
              })}
            </div>
          </motion.div>

        </div>
      </motion.div>
    </div>
  );
};

export default Learn;
